"""empty message

Revision ID: 225a544bc850
Revises: 
Create Date: 2019-02-21 08:34:14.047001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225a544bc850'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Rent', sa.Column('post_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Rent', 'post_by')
    # ### end Alembic commands ###
